name: Antora Documentation Build
# Based on https://github.com/OpenSimulationInterface/osi-documentation/blob/master/.github/workflows/antora-build.yml
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  trigger_antora:
    name: Trigger antora generator

    runs-on: Ubuntu-latest

    env:
      MUP_KEY: ${{ secrets.MACHINE_USER_PAT }}

    steps:
    - name: Trigger generator
      if: ${{ env.MUP_KEY != '' }}
      uses: peter-evans/repository-dispatch@v3
      with:
        token: ${{ secrets.MACHINE_USER_PAT }}
        event-type: antora-build-trigger
        repository:  # Add fork of https://code.asam.net/common/templates/antora-base-repo-example
        client-payload: '{"src": "${{ github.repository }}", "ref": "${{ github.ref }}", "sha": "${{ github.sha }}", "head_ref": "${{ github.head_ref }}"}'
        
